server:
  port: 50000

grpc:
  server:
    port: 50001

spring:
  application:
    name: invoke-grpc-student-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 12345678
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: cn.bklovezz.api.invokegrpcstudentservice.mybatis.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
